services:
  strfry:
    container_name: strfry
    image: notoshi/strfry:1.0.4u
    ports:
        - 7777:7777
    volumes:
        - ./strfry-db:/app/strfry-db
        - ./strfry.conf:/etc/strfry.conf
