---
listen: localhost:8080

favicon:

# your bostr address.
my_address: wss://bostr.example.com

# If relays is provided, then tracker could be optional
relays:
# - wss://relay.example1.com
# - wss://relay.example2.com

# If trackers is provided, then relays could be optional
trackers:
# - wss://tracker.example1.com
# - wss://tracker.example2.com

nip_11:
  name: bostr2
  description: Nostr relay bouncer
  software: git+https://codeberg.org/Yonle/bostr2
  pubkey: 0000000000000000000000000000000000000000000000000000000000000000
  contact: unset
  supported_nips:
  - 1
  - 2
  - 9
  - 11
  - 12
  - 15
  - 16
  - 20
  - 22
  - 33
  - 40
  - NOC-02

# 0 is infinity
max_connections_per_ip: 3

# user agent to use on connecting to upstream
user_agent: bostr2 (https://codeberg.org/Yonle/bostr2) on wss://bostr.example.com - nostr relay proxy aggregator

# whenever forward client ip to upstream.
forward_client_ip: false